[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = [
    'cd ProyectoBIB',
    'mvn clean package -DskipTests'
]

[phases.start]
cmd = 'cd ProyectoBIB && java -Dserver.port=$PORT -jar target/ProyectoBIB-0.0.1-SNAPSHOT.jar'
